language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t algorhythm92/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CLI=true algorhythm92/react-test npm test

after_success:
  # build all images for all containers
  - docker build -t algorhythm92/multi-client ./client
  - docker build -t algorhythm92/multi-nginx ./nginx
  - docker build -t algorhythm92/multi-server ./server
  - docker build -t algorhythm92/multi-worker ./worker
  # Log into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push all images to docker hub for our travis build to pull down
  - docker push algorhythm92/multi-client
  - docker push algorhythm92/multi-nginx
  - docker push algorhythm92/multi-server
  - docker push algorhythm92/multi-worker